# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to='avatar/%Y/%m/%d', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
